=== EXIficient/exificient/tags/release-0.7/data/schema/group2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:group name="custGroup">
        <xs:sequence>
            <xs:element name="customer" type="xs:string"/>
            <xs:element name="orderdetails" type="xs:string"/>
            <xs:element name="billto" type="xs:string"/>
            <xs:element name="shipto" type="xs:string"/>
        </xs:sequence>
    </xs:group>
    
    <xs:element name="order" type="ordertype"/>
    
    <xs:complexType name="ordertype">
        <xs:sequence>
            <xs:element name="o1">
                <xs:complexType>
                    <xs:group ref="custGroup"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="o2">
                <xs:complexType>
                    <xs:group ref="custGroup"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== EXIficient/exificient/tags/release-0.6/data/schema/group2.xml
<?xml version="1.0" encoding="UTF-8"?>
<order xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="group2.xsd" >
    <o1>
        <customer>C1</customer>
        <orderdetails>O1</orderdetails>
        <billto>B1</billto>
        <shipto>S1</shipto>
    </o1>
    <o2>
        <customer>C2</customer>
        <orderdetails>O2</orderdetails>
        <billto>B2</billto>
        <shipto>S2</shipto>
    </o2>
</order>
