<?xml version='1.0'?>
<!DOCTYPE kontakt [
    <!ELEMENT kontakt (name, email, telefon)>
    <!ELEMENT name (vorname, nachname)>
    <!ELEMENT vorname (#PCDATA)>
    <!ELEMENT nachname (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT telefon (#PCDATA)>
]>
<kontakt>
    <name>
        <vorname>Peter</vorname>
        <nachname>Mustermann</nachname>
    </name>
    <email>peter@firma.de</email>
    <telefon>+49(0711)123456</telefon>
</kontakt>
