=== EXIficient/exificient/tags/exificient-0.9.2/data/schema/identicalQName3.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	
    <xs:element name="qnames">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="valueDate">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="value">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="val" type="xs:date" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="valueFloat" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="value">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="val" type="xs:float" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="valueBoolean" type="ValueBoolean" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="ValueBoolean">
        <xs:sequence>
            <xs:element name="value">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="value2">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="val" type="xs:boolean" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
	
</xs:schema>

=== EXIficient/exificient/tags/release-0.8/data/schema/identicalQName3.xml
<?xml version="1.0" encoding="UTF-8"?>
<qnames xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="identicalQName3.xsd">
    <valueDate>
        <value>
            <val>2007-12-12</val>
        </value>
    </valueDate>
    <valueFloat>
        <value>
            <val>123.12</val>
        </value>
    </valueFloat>
    <valueBoolean>
        <value>
            <value2>
                <val>true</val>
            </value2>
        </value>
    </valueBoolean>
</qnames>
