=== EXIficient/exificient/tags/release-0.5/data/general/datatypeInteger.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="root" >
        <xs:complexType>
            <xs:sequence>
                <!-- Built-in Type: Integer -->
                <xs:element name="integer"  type="xs:integer" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="rInteger" minOccurs="0" maxOccurs="unbounded" >
                    <xs:simpleType>
                        <xs:restriction base="xs:integer"></xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="nonPositiveInteger"  type="xs:nonPositiveInteger" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="negativeInteger"  type="xs:negativeInteger" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="long"  type="xs:long" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="int"  type="xs:int" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="short"  type="xs:short" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="byte"  type="xs:byte" minOccurs="0" maxOccurs="unbounded" />
                <!-- Built-in Type: Unsigned Integer -->
                <xs:element name="nonNegativeInteger"  type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="unsignedLong"  type="xs:unsignedLong" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="positiveInteger"  type="xs:positiveInteger" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="unsignedInt"  type="xs:unsignedInt" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="unsignedShort"  type="xs:unsignedShort" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="unsignedByte"  type="xs:unsignedByte" minOccurs="0" maxOccurs="unbounded" />
                <!--  Built-in Type: N-Bit Integer  -->
                <xs:element name="bNBit" minOccurs="0" maxOccurs="unbounded" >
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="9999999999999999990"/>
                            <xs:maxInclusive value="9999999999999999999"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="lNBit" minOccurs="0" maxOccurs="unbounded" >
                    <xs:simpleType>
                        <xs:restriction base="xs:long">
                            <xs:minInclusive value="999999999999900"/>
                            <xs:maxInclusive value="999999999999999"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="iNBit" minOccurs="0" maxOccurs="unbounded" >
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="99999000"/>
                            <xs:maxInclusive value="99999999"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== EXIficient/exificient/tags/exificient-0.9.2/data/general/datatypeInteger.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="datatypeInteger.xsd">
    <!-- Built-in Type: Integer -->
    <integer>121</integer>
    <integer>11235451351531351</integer>
    <integer>-68168168468468435168168468468468846</integer>
    <rInteger>32183782190</rInteger>
    <nonPositiveInteger>-552</nonPositiveInteger>
    <negativeInteger>-4</negativeInteger>
    <long>2135151351</long>
    <long>1231538438555555559</long>
    <int>5435</int>
    <short>14155</short>
    <byte>106</byte>
    <nonNegativeInteger>0</nonNegativeInteger>
    <nonNegativeInteger>1816846816168161861616165156165</nonNegativeInteger>
    <unsignedLong>12678967543233</unsignedLong> 
    <positiveInteger>12135</positiveInteger>
    <unsignedInt>5858</unsignedInt>
    <unsignedShort>19955</unsignedShort>
    <unsignedByte>199</unsignedByte>
    <bNBit>9999999999999999995</bNBit>
    <lNBit>999999999999955</lNBit>
    <iNBit>99999555</iNBit>
</root>
