=== EXIficient/exificient/trunk/data/schema/wildcard2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:foo="http://www.siemens.com/foo" targetNamespace="http://www.siemens.com/foo"
  >

  <xs:element name="root">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element name="wildcardsNS" type="foo:WildcardsNS"/>
        <xs:element name="wildcards" type="foo:Wildcards"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Wildcards">
    <xs:sequence >
      <xs:any />
    </xs:sequence>
    <xs:anyAttribute/>
  </xs:complexType>

  <xs:complexType name="WildcardsNS">
    <xs:sequence >
      <xs:any namespace="http://www.siemens.com/foo"/>
    </xs:sequence>
    <xs:anyAttribute/>
  </xs:complexType>
  
  <xs:element name="elString" type="xs:string" />
  <xs:element name="elInt" type="xs:int" />


</xs:schema>

=== EXIficient/exificient/tags/release-0.4/data/schema/wildcard2.xml
<?xml version="1.0" encoding="UTF-8"?>
<foo:root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:foo="http://www.siemens.com/foo"
    xsi:schemaLocation="http://www.siemens.com/foo wildcard2.xsd" >
    <foo:wildcardsNS>
        <foo:elInt>123</foo:elInt>
    </foo:wildcardsNS>
    <foo:wildcards >
        <el xsi:type="xs:string">312</el>
    </foo:wildcards>
    <foo:wildcardsNS>
        <!-- invalid, approprioate namespace expected -->
        <!--<el xsi:type="xs:string">312</el>-->
        
        <!-- valid, right namespace -->
        <foo:elString>llk√∂k</foo:elString>
    </foo:wildcardsNS>
    <foo:wildcards >
        <foo:elInt>8</foo:elInt>
    </foo:wildcards>
</foo:root>
