=== EXIficient/exificient/tags/exificient-0.9.2/data/deviations/XMLSample.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="http://www.foo.com" xmlns:ns="http://www.foo.com">

  <xs:element name="personnel">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element name="person" type="ns:Person"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Person">
    <xs:sequence>
      <xs:element name="name" type="ns:Name"/>
      <xs:element name="email" type="xs:string"/>
      <xs:element name="yearsOfService" type="xs:nonNegativeInteger"/>
      <xs:element name="birthday" type="xs:date"/>
    </xs:sequence>
    <xs:attribute name="id" use="required" type="xs:NCName"/>
  </xs:complexType>

  <xs:complexType name="Name">
    <xs:sequence>
      <xs:element name="family" type="xs:string"/>
      <xs:element name="given" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== EXIficient/exificient/trunk/data/deviations/XMLSampleDevDatatype2.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!-- Sample XML Document --> 
<ns:personnel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.foo.com XMLSample.xsd"
 xmlns:ns="http://www.foo.com">
   <ns:person id="Boss" >
      <ns:name>
         <ns:family>Smith</ns:family>
         <ns:given>Bill</ns:given>
      </ns:name>
      <ns:email>smith@foo.com</ns:email>
      <ns:yearsOfService>20</ns:yearsOfService>
      <ns:birthday>1955-03-24 oder so !?!</ns:birthday>
   </ns:person>
   <!-- A second comment in this Sample XML Document -->
   <ns:person id="worker">
      <ns:name>
         <ns:family>Jones</ns:family>
         <ns:given>Bill</ns:given>
      </ns:name>
      <ns:email>jones@foo.com</ns:email>
      <ns:yearsOfService>5</ns:yearsOfService>
      <ns:birthday>1968-07-16</ns:birthday>
   </ns:person>
   <ns:person id="worker">
      <ns:name>
         <ns:family>Jones</ns:family>
         <ns:given>Sam</ns:given>
      </ns:name>
      <ns:email>sjones@foo.com</ns:email>
      <ns:yearsOfService>5</ns:yearsOfService>
      <ns:birthday>1959-01-26</ns:birthday>
   </ns:person>
</ns:personnel>
