=== EXIficient/exificient/tags/release-0.6/data/general/datatypeFloat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="root" >
        <xs:complexType>
            <xs:sequence>
                <!-- Built-in Type: Float -->
                <xs:element name="float"  type="xs:float" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="double"  type="xs:double" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== EXIficient/exificient/trunk/data/general/datatypeFloat.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="datatypeFloat.xsd">
    <!-- Built-in Type: Float -->
    <float>-1E4</float>
    <float>1267.43233E12</float>
    <float>12.78e-2</float>
    <float>12</float>
    <float>-0</float>
    <float>0</float>
    <float>INF</float>
    <float>NaN </float>
    <float>312321.4546</float>
    <double>-1E4</double>
    <double>1267.43233E12</double>
    <double>12.78e-2</double>
    <double>12</double>
    <double>-0</double>
    <double>0</double>
    <double>INF</double>
    <double>NaN</double>
    <double>12674123423.4323333312</double>
</root>
