=== EXIficient/exificient/tags/release-0.4/data/general/datatypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="root" >
        <xs:complexType>
            <xs:sequence>
                <!-- Built-in Type: Binary -->
                <xs:element name="base64Binary"  type="xs:base64Binary" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="hexBinary"  type="xs:hexBinary" minOccurs="0" maxOccurs="unbounded" />
                <!-- Built-in Type: Boolean {true, false, 1, 0} -->
                <xs:element name="boolean"  type="xs:boolean" minOccurs="0" maxOccurs="unbounded" />
                <!-- Built-in Type: Date-Time -->
                <xs:element name="dateTime"  type="xs:dateTime" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="time"  type="xs:time" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="date"  type="xs:date" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="gYearMonth"  type="xs:gYearMonth" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="gYear"  type="xs:gYear" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="gMonthDay"  type="xs:gMonthDay" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="gDay"  type="xs:gDay" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="gMonth"  type="xs:gMonth" minOccurs="0" maxOccurs="unbounded" />
                <!-- Built-in Type: Decimal -->
                <xs:element name="decimal"  type="xs:decimal" minOccurs="0" maxOccurs="unbounded" />
                <!-- Built-in Type: Float -->
                <xs:element name="float"  type="xs:float" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="double"  type="xs:double" minOccurs="0" maxOccurs="unbounded" />
                <!-- Built-in Type: Integer -->
                <xs:element name="integer"  type="xs:integer" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="nonPositiveInteger"  type="xs:nonPositiveInteger" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="negativeInteger"  type="xs:negativeInteger" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="long"  type="xs:long" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="int"  type="xs:int" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="short"  type="xs:short" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="byte"  type="xs:byte" minOccurs="0" maxOccurs="unbounded" />
                <!-- Built-in Type: Unsigned Integer -->
                <xs:element name="nonNegativeInteger"  type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="unsignedLong"  type="xs:unsignedLong" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="positiveInteger"  type="xs:positiveInteger" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="unsignedInt"  type="xs:unsignedInt" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="unsignedShort"  type="xs:unsignedShort" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="unsignedByte"  type="xs:unsignedByte" minOccurs="0" maxOccurs="unbounded" />
                <!-- Built-in Type: QName -->
                <xs:element name="qName"  type="xs:QName" minOccurs="0" maxOccurs="unbounded" />
                <!-- Built-in Type: List -->
                <!-- TODO: all typed derived by list, inclduing IDREFS and ENTITIES -->
                <xs:element name="intValues" minOccurs="0" maxOccurs="unbounded" >
                    <xs:simpleType>
                        <xs:list itemType="xs:integer"/>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="listDates"  minOccurs="0" maxOccurs="unbounded" >
                    <xs:simpleType>
                        <xs:list itemType="xs:date"/>
                    </xs:simpleType>
                </xs:element>
                <!-- Built-in Type: String -->
                <xs:element name="string"  type="xs:string" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="normalizedString"  type="xs:normalizedString" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="token"  type="xs:token" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="language"  type="xs:language" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="name"  type="xs:Name" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="nCName"  type="xs:NCName" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="iD"  type="xs:ID" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="iDREF"  type="xs:IDREF" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="eNTITY"  type="xs:ENTITY" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="nMTOKEN"  type="xs:NMTOKEN" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="anySimpleType"  type="xs:anySimpleType" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="anyURI"  type="xs:anyURI" minOccurs="0" maxOccurs="unbounded" />
                <!-- Built-in Type: RestrictedCharSet -->
                <xs:element name="rcs"  minOccurs="0" maxOccurs="unbounded" >
                    <xs:simpleType >
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Z]"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <!-- TODO Notation-->
                <!-- 
                <xs:element name="Notation" type="xs:Notation" minOccurs="0" maxOccurs="unbounded" />
                -->
                <xs:element name="duration"  type="xs:duration" minOccurs="0" maxOccurs="unbounded" />
                

                <!-- Built-in Type: Enumeration -->
                <xs:element name="car" minOccurs="0" maxOccurs="unbounded" >
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Audi"/>
                            <xs:enumeration value="Golf"/>
                            <xs:enumeration value="BMW"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== EXIficient/exificient/tags/exificient-0.9.2/data/general/datatypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="datatypes.xsd">
    
    <!-- http://xmlbeans.apache.org/docs/2.0.0/guide/conXMLBeansSupportBuiltInSchemaTypes.html -->
    <!-- Built-in Type: Binary -->
    <base64Binary>SMOkdHRlbiBIw7x0ZSBlaW4gw58gaW0g
        TmFtZW4sIHfDpHJlbiBzaWUgbcO2Z2xpY2hlcndlaXNlIGtlaW5lIEjDvHRlIG1laHIsDQpzb25kZXJuIEjDvMOfZS4NCg==
    
    
    
    
    </base64Binary>
    <hexBinary>0FB7</hexBinary>
    <hexBinary>0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef0123456789ABCDEFabcdef</hexBinary>
    <hexBinary>
        
        0FB8</hexBinary>
    
    <!-- Built-in Type: Boolean -->
    <boolean>true</boolean>
    <boolean>1</boolean>
    <boolean>false</boolean>
    <boolean>
        false  </boolean><!-- whitespace characters -->
    
    <!-- Built-in Type: Date-Time -->
    <dateTime>0001-01-01T01:03:12</dateTime>
    <dateTime>2005-01-01T00:00:00Z</dateTime>
    <dateTime>1979-01-01T00:00:00.0120</dateTime>
    <dateTime>0001-01-01T00:00:00.111+00:33</dateTime>
    <time>12:34:56</time>
    <time>00:55:19
    </time>
    
    <date>2002-10-11+13:00</date>
    <gYearMonth>1999-10</gYearMonth>
    <gYearMonth>1999-10Z</gYearMonth>
    <gYearMonth>1999-10-12:11</gYearMonth>
    <gYearMonth>1999-10+00:33</gYearMonth>
    <gYearMonth>1809-02Z</gYearMonth>
    <gYearMonth>
        
        1809-03Z</gYearMonth>
    
    <gYear>2007</gYear>
    <gYear>-0007</gYear>
    <gYear>2001Z</gYear>
    <gYear>2001+05:00</gYear>

    <gMonthDay>--01-28</gMonthDay>
    <gMonthDay>--01-28+00:00</gMonthDay>
    <gDay>---16</gDay>
    <gMonth>--12</gMonth>
    <gMonth>--12Z</gMonth>
 
    <!-- Built-in Type: Decimal -->
    <decimal>-1.23</decimal>
    <decimal>321.00045</decimal>
    <decimal>12678967.543233</decimal>
    <decimal>+100000.00</decimal>
    <decimal>210</decimal>
    <decimal>12678967.543233999999999999999999</decimal>
    <decimal>.234</decimal>
    <decimal>-.1</decimal>

    <!-- Built-in Type: Float -->
    <float>-1E4</float>
    <float>1267.43233E12</float>
    <float>12.78e-2</float>
    <float>12</float>
    <float>-0</float>
    <float>0</float>
    <float>INF</float>
    <float>NaN </float>
    <float>145345.66</float>
    <float>562949953421312</float>
    <double>-1E4</double>
    <double>1267.43233E12</double>
    <double>12.78e-2</double>
    <double>12</double>
    <double>-0</double>
    <double>0</double>
    <double>INF</double>
    <double>NaN</double>

    <!-- Built-in Type: Integer -->
    <integer>121</integer>
    <integer>11235451351531351</integer>
    <integer>-68168168468468435168168468468468846</integer>
    <nonPositiveInteger>-552</nonPositiveInteger>
    <nonPositiveInteger>-5525454654654654564564564564</nonPositiveInteger>
    <negativeInteger>-4</negativeInteger>
    <negativeInteger>-455588111111111111111111111111</negativeInteger>
    <long>2135151351</long>
    <long>1231538438555555559</long>
    <int>5435</int>
    <short>14155</short>
    <byte>106</byte>
    <nonNegativeInteger>0</nonNegativeInteger>
    <nonNegativeInteger>1816846816168161861616165156165</nonNegativeInteger>
    <unsignedLong>12678967543233</unsignedLong> 
    <positiveInteger>12135</positiveInteger>
    <positiveInteger>1213567890123456789</positiveInteger>
    <unsignedInt>5858</unsignedInt>
    <unsignedShort>19955</unsignedShort>
    <unsignedByte>199</unsignedByte>
    
    <!-- Built-in Type: QName -->
    <qName>ss</qName>
    
    <!-- Built-in Type: List -->
    <intValues>100 34 56 -23 1567</intValues>
    <listDates>2077-12-12 1999-01-02</listDates>
    <listBytes>+1 0 127 -127</listBytes>
    <listBytes></listBytes>
    <listFloats>1e4 -10000 5.234e-2</listFloats>
    <listOfEnums>--12-25 --08-15 --01-01 --07-14</listOfEnums><!--   - -12-25  - -08-15  - -01-01  - -07-14       -->
    
    <!-- Built-in Type: String  -->
    <string>ss ss </string>
    <string>&#x1D11E;</string> <!-- high/low surrogate pairs for U+1D11E == 119070 -->
    <string>foo &#x2000B; blaa</string>
    <string></string>   <!--  *Empty* strings -->
    <string />
    <normalizedString> dasdas     dasdas</normalizedString>
    <token>dasdasdas</token>
    <language>en</language>
    <name>dasda</name>
   <nCName>ww</nCName>
    <iD>s55</iD>
    <iD>ID000</iD>
    <iDREF>ID000</iDREF>
    <nMTOKEN>da</nMTOKEN>
    <anySimpleType>ssd</anySimpleType>
    <anyURI>http://www.w3.org/TR/xmlschema-2/#anyURI</anyURI>
    <!-- Built-in Type: RestrictedCharSet -->
    <rcs>A</rcs>
    <rcs>Z</rcs>
    
    <!-- 
    <Notation></Notation>
    -->
    <duration>P1Y2MT2H</duration>
    <duration>P0Y1347M0D</duration>
    <duration>-P1347M</duration>
    
    <!-- Built-in Type: Enumeration -->
    <enumStrings>BMW</enumStrings>
    <enumInts>-0</enumInts>
    <enumInts>+1</enumInts>
    <enumInts>+1</enumInts>
    <enumInts>2</enumInts>
    <enumInts>8</enumInts>
    <enumInts>9</enumInts>
    
</root>
